//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum media_codec_type {
  media_codec_type_none = 0,
  media_codec_type_siren14 = 1,
  media_codec_type_pcmu = 2,
  media_codec_type_nm = 3,
  media_codec_type_speex = 4,
  media_codec_type_siren7 = 5,
  media_codec_type_opus = 6
}
