//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ND_TEST_TYPE {
  ND_TEST_LOCATE_INTERFACE = 0,
  ND_TEST_PING_GATEWAY = 1,
  ND_TEST_DNS = 2,
  ND_TEST_STUN = 3,
  ND_TEST_ECHO = 4,
  ND_TEST_ECHO_SIP_FIRST_PORT = 5,
  ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_REQUEST = 6,
  ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_RESPONSE = 7,
  ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_REQUEST = 8,
  ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_RESPONSE = 9,
  ND_TEST_ECHO_SIP_SECOND_PORT = 10,
  ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_REQUEST = 11,
  ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_RESPONSE = 12,
  ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_REQUEST = 13,
  ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_RESPONSE = 14,
  ND_TEST_ECHO_MEDIA = 15,
  ND_TEST_ECHO_MEDIA_LARGE_PACKET = 16
}
