//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_application_state_notification_type_t {
  vx_application_state_notification_type_before_background = 0,
  vx_application_state_notification_type_after_foreground = 1,
  vx_application_state_notification_type_periodic_background_idle = 2
}
