//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_audio_device_hot_swap_event_type_t {
  vx_audio_device_hot_swap_event_type_disabled_due_to_platform_constraints = 0,
  vx_audio_device_hot_swap_event_type_active_render_device_changed = 1,
  vx_audio_device_hot_swap_event_type_active_capture_device_changed = 2,
  vx_audio_device_hot_swap_event_type_audio_device_added = 3,
  vx_audio_device_hot_swap_event_type_audio_device_removed = 4
}
