//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_attempt_stun {
  attempt_stun_unspecified = 0,
  attempt_stun_on = 1,
  attempt_stun_off = 2
}
