//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_buddy_management_mode {
  mode_auto_accept = 0,
  mode_auto_add = 1,
  mode_block = 2,
  mode_hide = 3,
  mode_application = 4
}
