//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_channel_mode {
  channel_mode_none = 0,
  channel_mode_normal = 1,
  channel_mode_presentation = 2,
  channel_mode_lecture = 3,
  channel_mode_open = 4,
  channel_mode_auditorium = 5
}
