//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_crash_test_type_t {
  vx_crash_access_zero_pointer = 0,
  vx_crash_access_violation = 1,
  vx_crash_stack_overflow = 2,
  vx_crash_heap_corruption = 3
}
