//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_control_communications_operation {
  vx_control_communications_operation_block = 0,
  vx_control_communications_operation_unblock = 1,
  vx_control_communications_operation_list = 2,
  vx_control_communications_operation_clear = 3
}
