//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_diagnostic_dump_level {
  diagnostic_dump_level_all = 0,
  diagnostic_dump_level_sessions = 1
}
