//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_dtmf_type {
  dtmf_0 = 0,
  dtmf_1 = 1,
  dtmf_2 = 2,
  dtmf_3 = 3,
  dtmf_4 = 4,
  dtmf_5 = 5,
  dtmf_6 = 6,
  dtmf_7 = 7,
  dtmf_8 = 8,
  dtmf_9 = 9,
  dtmf_pound = 10,
  dtmf_star = 11,
  dtmf_A = 12,
  dtmf_B = 13,
  dtmf_C = 14,
  dtmf_D = 15,
  dtmf_max = dtmf_D
}
