//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_device_type_t {
  vx_device_type_specific_device = 0,
  vx_device_type_default_system = 1,
  vx_device_type_null = 2,
  vx_device_type_default_communication = 3
}
