//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_evt_network_message_type {
  vx_evt_network_message_type_offline_message = 1,
  vx_evt_network_message_type_admin_message = 2,
  vx_evt_network_message_type_sessionless_message = 3
}
