//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_event_type {
  evt_none = 0,
  evt_account_login_state_change = 2,
  evt_buddy_presence = 7,
  evt_subscription = 8,
  evt_session_notification = 9,
  evt_message = 10,
  evt_aux_audio_properties = 11,
  evt_buddy_changed = 15,
  evt_buddy_group_changed = 16,
  evt_buddy_and_group_list_changed = 17,
  evt_keyboard_mouse = 18,
  evt_idle_state_changed = 19,
  evt_media_stream_updated = 20,
  evt_text_stream_updated = 21,
  evt_sessiongroup_added = 22,
  evt_sessiongroup_removed = 23,
  evt_session_added = 24,
  evt_session_removed = 25,
  evt_participant_added = 26,
  evt_participant_removed = 27,
  evt_participant_updated = 28,
  evt_sessiongroup_playback_frame_played = 30,
  evt_session_updated = 31,
  evt_sessiongroup_updated = 32,
  evt_media_completion = 33,
  evt_server_app_data = 35,
  evt_user_app_data = 36,
  evt_network_message = 38,
  evt_voice_service_connection_state_changed = 39,
  evt_publication_state_changed = 40,
  evt_audio_device_hot_swap = 41,
  evt_user_to_user_message = 42,
  evt_session_archive_message = 43,
  evt_session_archive_query_end = 44,
  evt_account_archive_message = 45,
  evt_account_archive_query_end = 46,
  evt_account_send_message_failed = 47,
  evt_transcribed_message = 48,
  evt_max = evt_transcribed_message+1
}
