//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_evt_subscription_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_evt_subscription_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_evt_subscription_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_evt_subscription_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_evt_subscription_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vx_evt_base_t base_ {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_base__set(swigCPtr, vx_evt_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_base__get(swigCPtr);
      vx_evt_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_evt_base_t(cPtr, false);
      return ret;
    } 
  }

  public string account_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_account_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_account_handle_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_uri {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_buddy_uri_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_buddy_uri_get(swigCPtr);
      return ret;
    } 
  }

  public string subscription_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_subscription_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_subscription_handle_get(swigCPtr);
      return ret;
    } 
  }

  public vx_subscription_type subscription_type {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_subscription_type_set(swigCPtr, (int)value);
    } 
    get {
      vx_subscription_type ret = (vx_subscription_type)VivoxCoreInstancePINVOKE.vx_evt_subscription_t_subscription_type_get(swigCPtr);
      return ret;
    } 
  }

  public string displayname {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_displayname_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_displayname_get(swigCPtr);
      return ret;
    } 
  }

  public string application {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_application_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_application_get(swigCPtr);
      return ret;
    } 
  }

  public string message {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_subscription_t_message_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_subscription_t_message_get(swigCPtr);
      return ret;
    } 
  }

  public vx_evt_subscription_t() : this(VivoxCoreInstancePINVOKE.new_vx_evt_subscription_t(), true) {
  }

}
