//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_evt_participant_updated_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_evt_participant_updated_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_evt_participant_updated_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_evt_participant_updated_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_evt_participant_updated_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vx_evt_base_t base_ {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_base__set(swigCPtr, vx_evt_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_base__get(swigCPtr);
      vx_evt_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_evt_base_t(cPtr, false);
      return ret;
    } 
  }

  public string sessiongroup_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_sessiongroup_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_sessiongroup_handle_get(swigCPtr);
      return ret;
    } 
  }

  public string session_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_session_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_session_handle_get(swigCPtr);
      return ret;
    } 
  }

  public string participant_uri {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_participant_uri_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_participant_uri_get(swigCPtr);
      return ret;
    } 
  }

  public int is_moderator_muted {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_moderator_muted_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_moderator_muted_get(swigCPtr);
      return ret;
    } 
  }

  public int is_speaking {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_speaking_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_speaking_get(swigCPtr);
      return ret;
    } 
  }

  public int volume {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_volume_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_volume_get(swigCPtr);
      return ret;
    } 
  }

  public double energy {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_energy_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_energy_get(swigCPtr);
      return ret;
    } 
  }

  public int active_media {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_active_media_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_active_media_get(swigCPtr);
      return ret;
    } 
  }

  public int is_muted_for_me {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_muted_for_me_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_muted_for_me_get(swigCPtr);
      return ret;
    } 
  }

  public int is_text_muted_for_me {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_text_muted_for_me_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_text_muted_for_me_get(swigCPtr);
      return ret;
    } 
  }

  public int is_moderator_text_muted {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_moderator_text_muted_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_moderator_text_muted_get(swigCPtr);
      return ret;
    } 
  }

  public vx_participant_type type {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_type_set(swigCPtr, (int)value);
    } 
    get {
      vx_participant_type ret = (vx_participant_type)VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_type_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_vx_participant_diagnostic_state_t diagnostic_states {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_diagnostic_states_set(swigCPtr, SWIGTYPE_p_vx_participant_diagnostic_state_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_diagnostic_states_get(swigCPtr);
      SWIGTYPE_p_vx_participant_diagnostic_state_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_vx_participant_diagnostic_state_t(cPtr, false);
      return ret;
    } 
  }

  public int diagnostic_state_count {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_diagnostic_state_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_diagnostic_state_count_get(swigCPtr);
      return ret;
    } 
  }

  public string alias_username {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_alias_username_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_alias_username_get(swigCPtr);
      return ret;
    } 
  }

  public string encoded_uri_with_tag {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_encoded_uri_with_tag_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_encoded_uri_with_tag_get(swigCPtr);
      return ret;
    } 
  }

  public int is_current_user {
    set {
      VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_current_user_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_evt_participant_updated_t_is_current_user_get(swigCPtr);
      return ret;
    } 
  }

  public vx_evt_participant_updated_t() : this(VivoxCoreInstancePINVOKE.new_vx_evt_participant_updated_t(), true) {
  }

}
