//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_generic_credentials : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_generic_credentials(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_generic_credentials obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_generic_credentials() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_generic_credentials(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string admin_username {
    set {
      VivoxCoreInstancePINVOKE.vx_generic_credentials_admin_username_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_generic_credentials_admin_username_get(swigCPtr);
      return ret;
    } 
  }

  public string admin_password {
    set {
      VivoxCoreInstancePINVOKE.vx_generic_credentials_admin_password_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_generic_credentials_admin_password_get(swigCPtr);
      return ret;
    } 
  }

  public string grant_document {
    set {
      VivoxCoreInstancePINVOKE.vx_generic_credentials_grant_document_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_generic_credentials_grant_document_get(swigCPtr);
      return ret;
    } 
  }

  public string server_url {
    set {
      VivoxCoreInstancePINVOKE.vx_generic_credentials_server_url_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_generic_credentials_server_url_get(swigCPtr);
      return ret;
    } 
  }

  public vx_generic_credentials() : this(VivoxCoreInstancePINVOKE.new_vx_generic_credentials(), true) {
  }

}
