//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_log_level {
  log_none = -1,
  log_error = 0,
  log_warning = 1,
  log_info = 2,
  log_debug = 3,
  log_trace = 4,
  log_all = 5
}
