//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_log_type {
  log_to_none = 0,
  log_to_file = 1,
  log_to_callback = 2,
  log_to_file_and_callback = 3
}
