//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_login_state_change_state {
  login_state_logged_out = 0,
  login_state_logged_in = 1,
  login_state_logging_in = 2,
  login_state_logging_out = 3,
  login_state_resetting = 4,
  login_state_error = 100
}
