//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_media_type {
  media_type_none = 0,
  media_type_text = 1,
  media_type_audio = 2,
  media_type_video = 3,
  media_type_audiovideo = 4
}
