//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_media_completion_type {
  media_completion_type_none = 0,
  aux_buffer_audio_capture = 1,
  aux_buffer_audio_render = 2,
  sessiongroup_audio_injection = 3
}
