//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_opus_bandwidth {
  opus_bandwidth_auto = 0,
  opus_bandwidth_nb = 1,
  opus_bandwidth_mb = 2,
  opus_bandwidth_wb = 3,
  opus_bandwidth_swb = 4,
  opus_bandwidth_fb = 5
}
