//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_opus_vbr_mode {
  opus_mode_cbr = 0,
  opus_mode_lvbr = 1,
  opus_mode_vbr = 2
}
