//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_password_hash_algorithm_t {
  password_hash_algorithm_cleartext = 0,
  password_hash_algorithm_sha1_username_hash = 1
}
