//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_publication_state_change_state {
  publication_state_success = 0,
  publication_state_transient_error = 1,
  publication_state_permanent_error = 2
}
