//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_participant_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_participant_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_participant_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_participant_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_participant_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string uri {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_uri_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_participant_t_uri_get(swigCPtr);
      return ret;
    } 
  }

  public string first_name {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_first_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_participant_t_first_name_get(swigCPtr);
      return ret;
    } 
  }

  public string last_name {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_last_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_participant_t_last_name_get(swigCPtr);
      return ret;
    } 
  }

  public string display_name {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_display_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_participant_t_display_name_get(swigCPtr);
      return ret;
    } 
  }

  public string username {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_username_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_participant_t_username_get(swigCPtr);
      return ret;
    } 
  }

  public int is_moderator {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_is_moderator_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_participant_t_is_moderator_get(swigCPtr);
      return ret;
    } 
  }

  public int is_moderator_muted {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_is_moderator_muted_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_participant_t_is_moderator_muted_get(swigCPtr);
      return ret;
    } 
  }

  public int is_moderator_text_muted {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_is_moderator_text_muted_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_participant_t_is_moderator_text_muted_get(swigCPtr);
      return ret;
    } 
  }

  public int is_muted_for_me {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_is_muted_for_me_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_participant_t_is_muted_for_me_get(swigCPtr);
      return ret;
    } 
  }

  public int is_owner {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_is_owner_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_participant_t_is_owner_get(swigCPtr);
      return ret;
    } 
  }

  public int account_id {
    set {
      VivoxCoreInstancePINVOKE.vx_participant_t_account_id_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_participant_t_account_id_get(swigCPtr);
      return ret;
    } 
  }

  public vx_participant_t() : this(VivoxCoreInstancePINVOKE.new_vx_participant_t(), true) {
  }

}
