//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_participant_type {
  participant_user = 0,
  part_user = participant_user,
  participant_moderator = 1,
  part_moderator = participant_moderator,
  participant_owner = 2,
  part_focus = participant_owner
}
