//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_participant_removed_reason {
  participant_left = 0,
  participant_timeout = 1,
  participant_kicked = 2,
  participant_banned = 3
}
