//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_req_connector_create_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_req_connector_create_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_req_connector_create_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_req_connector_create_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_req_connector_create_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

        public static implicit operator vx_req_base_t(vx_req_connector_create_t t) {
            return t.base_;
        }
        
  public vx_req_base_t base_ {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_base__set(swigCPtr, vx_req_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_base__get(swigCPtr);
      vx_req_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_req_base_t(cPtr, false);
      return ret;
    } 
  }

  public string client_name {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_client_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_client_name_get(swigCPtr);
      return ret;
    } 
  }

  public string acct_mgmt_server {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_acct_mgmt_server_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_acct_mgmt_server_get(swigCPtr);
      return ret;
    } 
  }

  public int minimum_port {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_minimum_port_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_minimum_port_get(swigCPtr);
      return ret;
    } 
  }

  public int maximum_port {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_maximum_port_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_maximum_port_get(swigCPtr);
      return ret;
    } 
  }

  public vx_attempt_stun attempt_stun {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_attempt_stun_set(swigCPtr, (int)value);
    } 
    get {
      vx_attempt_stun ret = (vx_attempt_stun)VivoxCoreInstancePINVOKE.vx_req_connector_create_t_attempt_stun_get(swigCPtr);
      return ret;
    } 
  }

  public vx_connector_mode mode {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_mode_set(swigCPtr, (int)value);
    } 
    get {
      vx_connector_mode ret = (vx_connector_mode)VivoxCoreInstancePINVOKE.vx_req_connector_create_t_mode_get(swigCPtr);
      return ret;
    } 
  }

  public string log_folder {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_folder_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_folder_get(swigCPtr);
      return ret;
    } 
  }

  public string log_filename_prefix {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_filename_prefix_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_filename_prefix_get(swigCPtr);
      return ret;
    } 
  }

  public string log_filename_suffix {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_filename_suffix_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_filename_suffix_get(swigCPtr);
      return ret;
    } 
  }

  public int log_level {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_level_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_log_level_get(swigCPtr);
      return ret;
    } 
  }

  public vx_session_handle_type session_handle_type {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_session_handle_type_set(swigCPtr, (int)value);
    } 
    get {
      vx_session_handle_type ret = (vx_session_handle_type)VivoxCoreInstancePINVOKE.vx_req_connector_create_t_session_handle_type_get(swigCPtr);
      return ret;
    } 
  }

  public string application {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_application_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_application_get(swigCPtr);
      return ret;
    } 
  }

  public int max_calls {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_max_calls_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_max_calls_get(swigCPtr);
      return ret;
    } 
  }

  public int allow_cross_domain_logins {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_allow_cross_domain_logins_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_allow_cross_domain_logins_get(swigCPtr);
      return ret;
    } 
  }

  public int default_codec {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_default_codec_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_default_codec_get(swigCPtr);
      return ret;
    } 
  }

  public string user_agent_id {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_user_agent_id_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_user_agent_id_get(swigCPtr);
      return ret;
    } 
  }

  public string media_probe_server {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_media_probe_server_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_media_probe_server_get(swigCPtr);
      return ret;
    } 
  }

  public string http_proxy_server_name {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_http_proxy_server_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_http_proxy_server_name_get(swigCPtr);
      return ret;
    } 
  }

  public int http_proxy_server_port {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_http_proxy_server_port_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_http_proxy_server_port_get(swigCPtr);
      return ret;
    } 
  }

  public int enable_duplicate_participant_uris {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_enable_duplicate_participant_uris_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_enable_duplicate_participant_uris_get(swigCPtr);
      return ret;
    } 
  }

  public string connector_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_connector_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_connector_handle_get(swigCPtr);
      return ret;
    } 
  }

  public uint configured_codecs {
    set {
      VivoxCoreInstancePINVOKE.vx_req_connector_create_t_configured_codecs_set(swigCPtr, value);
    } 
    get {
      uint ret = VivoxCoreInstancePINVOKE.vx_req_connector_create_t_configured_codecs_get(swigCPtr);
      return ret;
    } 
  }

  public vx_req_connector_create_t() : this(VivoxCoreInstancePINVOKE.new_vx_req_connector_create_t(), true) {
  }

}
