//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_req_account_buddy_search_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_req_account_buddy_search_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_req_account_buddy_search_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_req_account_buddy_search_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_req_account_buddy_search_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

        public static implicit operator vx_req_base_t(vx_req_account_buddy_search_t t) {
            return t.base_;
        }
        
  public vx_req_base_t base_ {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_base__set(swigCPtr, vx_req_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_base__get(swigCPtr);
      vx_req_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_req_base_t(cPtr, false);
      return ret;
    } 
  }

  public string account_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_account_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_account_handle_get(swigCPtr);
      return ret;
    } 
  }

  public int page_number {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_page_number_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_page_number_get(swigCPtr);
      return ret;
    } 
  }

  public int page_size {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_page_size_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_page_size_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_first_name {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_first_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_first_name_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_last_name {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_last_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_last_name_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_user_name {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_user_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_user_name_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_email {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_email_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_email_get(swigCPtr);
      return ret;
    } 
  }

  public int begins_with {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_begins_with_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_begins_with_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_display_name {
    set {
      VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_display_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_account_buddy_search_t_buddy_display_name_get(swigCPtr);
      return ret;
    } 
  }

  public vx_req_account_buddy_search_t() : this(VivoxCoreInstancePINVOKE.new_vx_req_account_buddy_search_t(), true) {
  }

}
