//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_resp_sessiongroup_get_stats_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_resp_sessiongroup_get_stats_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_resp_sessiongroup_get_stats_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_resp_sessiongroup_get_stats_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_resp_sessiongroup_get_stats_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vx_resp_base_t base_ {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_base__set(swigCPtr, vx_resp_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_base__get(swigCPtr);
      vx_resp_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_resp_base_t(cPtr, false);
      return ret;
    } 
  }

  public int insufficient_bandwidth {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_insufficient_bandwidth_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_insufficient_bandwidth_get(swigCPtr);
      return ret;
    } 
  }

  public int min_bars {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_min_bars_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_min_bars_get(swigCPtr);
      return ret;
    } 
  }

  public int max_bars {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_max_bars_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_max_bars_get(swigCPtr);
      return ret;
    } 
  }

  public int current_bars {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_bars_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_bars_get(swigCPtr);
      return ret;
    } 
  }

  public int pk_loss {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_pk_loss_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_pk_loss_get(swigCPtr);
      return ret;
    } 
  }

  public int incoming_received {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_received_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_received_get(swigCPtr);
      return ret;
    } 
  }

  public int incoming_expected {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_expected_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_expected_get(swigCPtr);
      return ret;
    } 
  }

  public int incoming_packetloss {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_packetloss_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_packetloss_get(swigCPtr);
      return ret;
    } 
  }

  public int incoming_out_of_time {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_out_of_time_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_out_of_time_get(swigCPtr);
      return ret;
    } 
  }

  public int incoming_discarded {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_discarded_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_incoming_discarded_get(swigCPtr);
      return ret;
    } 
  }

  public int outgoing_sent {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_outgoing_sent_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_outgoing_sent_get(swigCPtr);
      return ret;
    } 
  }

  public int render_device_underruns {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_render_device_underruns_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_render_device_underruns_get(swigCPtr);
      return ret;
    } 
  }

  public int render_device_overruns {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_render_device_overruns_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_render_device_overruns_get(swigCPtr);
      return ret;
    } 
  }

  public int render_device_errors {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_render_device_errors_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_render_device_errors_get(swigCPtr);
      return ret;
    } 
  }

  public string call_id {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_call_id_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_call_id_get(swigCPtr);
      return ret;
    } 
  }

  public int plc_on {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_plc_on_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_plc_on_get(swigCPtr);
      return ret;
    } 
  }

  public int plc_synthetic_frames {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_plc_synthetic_frames_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_plc_synthetic_frames_get(swigCPtr);
      return ret;
    } 
  }

  public string codec_name {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_codec_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_codec_name_get(swigCPtr);
      return ret;
    } 
  }

  public int codec_mode {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_codec_mode_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_codec_mode_get(swigCPtr);
      return ret;
    } 
  }

  public double min_latency {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_min_latency_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_min_latency_get(swigCPtr);
      return ret;
    } 
  }

  public double max_latency {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_max_latency_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_max_latency_get(swigCPtr);
      return ret;
    } 
  }

  public int latency_measurement_count {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_measurement_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_measurement_count_get(swigCPtr);
      return ret;
    } 
  }

  public double latency_sum {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_sum_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_sum_get(swigCPtr);
      return ret;
    } 
  }

  public double last_latency_measured {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_last_latency_measured_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_last_latency_measured_get(swigCPtr);
      return ret;
    } 
  }

  public int latency_packets_lost {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_lost_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_lost_get(swigCPtr);
      return ret;
    } 
  }

  public double r_factor {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_r_factor_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_r_factor_get(swigCPtr);
      return ret;
    } 
  }

  public int latency_packets_sent {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_sent_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_sent_get(swigCPtr);
      return ret;
    } 
  }

  public int latency_packets_dropped {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_dropped_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_dropped_get(swigCPtr);
      return ret;
    } 
  }

  public int latency_packets_malformed {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_malformed_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_malformed_get(swigCPtr);
      return ret;
    } 
  }

  public int latency_packets_negative_latency {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_negative_latency_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_latency_packets_negative_latency_get(swigCPtr);
      return ret;
    } 
  }

  public double sample_interval_begin {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_sample_interval_begin_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_sample_interval_begin_get(swigCPtr);
      return ret;
    } 
  }

  public double sample_interval_end {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_sample_interval_end_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_sample_interval_end_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_int capture_device_consecutively_read_count {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_capture_device_consecutively_read_count_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_capture_device_consecutively_read_count_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public int current_opus_bit_rate {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_bit_rate_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_bit_rate_get(swigCPtr);
      return ret;
    } 
  }

  public int current_opus_complexity {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_complexity_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_complexity_get(swigCPtr);
      return ret;
    } 
  }

  public int current_opus_vbr_mode {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_vbr_mode_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_vbr_mode_get(swigCPtr);
      return ret;
    } 
  }

  public int current_opus_bandwidth {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_bandwidth_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_bandwidth_get(swigCPtr);
      return ret;
    } 
  }

  public int current_opus_max_packet_size {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_max_packet_size_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_current_opus_max_packet_size_get(swigCPtr);
      return ret;
    } 
  }

  public int signal_secure {
    set {
      VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_signal_secure_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_resp_sessiongroup_get_stats_t_signal_secure_get(swigCPtr);
      return ret;
    } 
  }

  public vx_resp_sessiongroup_get_stats_t() : this(VivoxCoreInstancePINVOKE.new_vx_resp_sessiongroup_get_stats_t(), true) {
  }

}
