//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_req_session_set_3d_position_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_req_session_set_3d_position_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_req_session_set_3d_position_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_req_session_set_3d_position_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_req_session_set_3d_position_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

        public static implicit operator vx_req_base_t(vx_req_session_set_3d_position_t t) {
            return t.base_;
        }
        
  public vx_req_base_t base_ {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_base__set(swigCPtr, vx_req_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_base__get(swigCPtr);
      vx_req_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_req_base_t(cPtr, false);
      return ret;
    } 
  }

  public string session_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_session_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_session_handle_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_double speaker_position {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_position_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_position_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double speaker_velocity {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_velocity_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_velocity_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double speaker_at_orientation {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_at_orientation_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_at_orientation_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double speaker_up_orientation {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_up_orientation_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_up_orientation_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double speaker_left_orientation {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_left_orientation_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_speaker_left_orientation_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double listener_position {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_position_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_position_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double listener_velocity {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_velocity_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_velocity_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double listener_at_orientation {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_at_orientation_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_at_orientation_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double listener_up_orientation {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_up_orientation_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_up_orientation_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double listener_left_orientation {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_left_orientation_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_listener_left_orientation_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public orientation_type type {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_type_set(swigCPtr, (int)value);
    } 
    get {
      orientation_type ret = (orientation_type)VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_type_get(swigCPtr);
      return ret;
    } 
  }

  public req_disposition_type_t req_disposition_type {
    set {
      VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_req_disposition_type_set(swigCPtr, (int)value);
    } 
    get {
      req_disposition_type_t ret = (req_disposition_type_t)VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_req_disposition_type_get(swigCPtr);
      return ret;
    } 
  }

  public vx_req_session_set_3d_position_t() : this(VivoxCoreInstancePINVOKE.new_vx_req_session_set_3d_position_t(), true) {
  }

  public void Set3DPosition(float[] speakerPos, float[] listenerPos, float[] listenerAtOrient, float[] listenerUpOrient) {
    VivoxCoreInstancePINVOKE.vx_req_session_set_3d_position_t_Set3DPosition(swigCPtr, speakerPos, listenerPos, listenerAtOrient, listenerUpOrient);
  }

}
