//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_recording_frame_type_t {
  VX_RECORDING_FRAME_TYPE_DELTA = 0,
  VX_RECORDING_FRAME_TYPE_CONTROL = 1
}
