//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_req_base_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_req_base_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_req_base_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_req_base_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_req_base_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vx_message_base_t message {
    set {
      VivoxCoreInstancePINVOKE.vx_req_base_t_message_set(swigCPtr, vx_message_base_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_base_t_message_get(swigCPtr);
      vx_message_base_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_message_base_t(cPtr, false);
      return ret;
    } 
  }

  public vx_request_type type {
    set {
      VivoxCoreInstancePINVOKE.vx_req_base_t_type_set(swigCPtr, (int)value);
    } 
    get {
      vx_request_type ret = (vx_request_type)VivoxCoreInstancePINVOKE.vx_req_base_t_type_get(swigCPtr);
      return ret;
    } 
  }

  public string cookie {
    set {
      VivoxCoreInstancePINVOKE.vx_req_base_t_cookie_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_req_base_t_cookie_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void vcookie {
    set {
      VivoxCoreInstancePINVOKE.vx_req_base_t_vcookie_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_req_base_t_vcookie_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public vx_req_base_t() : this(VivoxCoreInstancePINVOKE.new_vx_req_base_t(), true) {
  }

}
