//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_system_stats_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_system_stats_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_system_stats_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_system_stats_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_system_stats_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int ss_size {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ss_size_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_ss_size_get(swigCPtr);
      return ret;
    } 
  }

  public int ar_source_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_count_get(swigCPtr);
      return ret;
    } 
  }

  public int ar_source_queue_limit {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_queue_limit_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_queue_limit_get(swigCPtr);
      return ret;
    } 
  }

  public int ar_source_queue_overflows {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_queue_overflows_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_queue_overflows_get(swigCPtr);
      return ret;
    } 
  }

  public int ar_source_poll_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_poll_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_poll_count_get(swigCPtr);
      return ret;
    } 
  }

  public uint msgovrld_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_msgovrld_count_set(swigCPtr, value);
    } 
    get {
      uint ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_msgovrld_count_get(swigCPtr);
      return ret;
    } 
  }

  public vx_stat_sample_t ar_source_free_buffers {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_free_buffers_set(swigCPtr, vx_stat_sample_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_free_buffers_get(swigCPtr);
      vx_stat_sample_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_stat_sample_t(cPtr, false);
      return ret;
    } 
  }

  public vx_stat_sample_t ar_source_queue_depth {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_queue_depth_set(swigCPtr, vx_stat_sample_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_system_stats_t_ar_source_queue_depth_get(swigCPtr);
      vx_stat_sample_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_stat_sample_t(cPtr, false);
      return ret;
    } 
  }

  public vx_stat_thread_t vp_thread {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_vp_thread_set(swigCPtr, vx_stat_thread_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_system_stats_t_vp_thread_get(swigCPtr);
      vx_stat_thread_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_stat_thread_t(cPtr, false);
      return ret;
    } 
  }

  public vx_stat_thread_t ticker_thread {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_ticker_thread_set(swigCPtr, vx_stat_thread_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_system_stats_t_ticker_thread_get(swigCPtr);
      vx_stat_thread_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new vx_stat_thread_t(cPtr, false);
      return ret;
    } 
  }

  public int clnt_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_clnt_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_clnt_count_get(swigCPtr);
      return ret;
    } 
  }

  public int lc_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_lc_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_lc_count_get(swigCPtr);
      return ret;
    } 
  }

  public int mps_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_mps_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_mps_count_get(swigCPtr);
      return ret;
    } 
  }

  public int mpsg_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_mpsg_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_mpsg_count_get(swigCPtr);
      return ret;
    } 
  }

  public int strms_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_strms_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_strms_count_get(swigCPtr);
      return ret;
    } 
  }

  public int strr_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_strr_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_strr_count_get(swigCPtr);
      return ret;
    } 
  }

  public int strss_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_strss_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_strss_count_get(swigCPtr);
      return ret;
    } 
  }

  public int vp_count {
    set {
      VivoxCoreInstancePINVOKE.vx_system_stats_t_vp_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_system_stats_t_vp_count_get(swigCPtr);
      return ret;
    } 
  }

  public vx_system_stats_t() : this(VivoxCoreInstancePINVOKE.new_vx_system_stats_t(), true) {
  }

}
