//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_state_sessiongroup_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_state_sessiongroup_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_state_sessiongroup_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_state_sessiongroup_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_state_sessiongroup_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string sessiongroup_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_sessiongroup_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_sessiongroup_handle_get(swigCPtr);
      return ret;
    } 
  }

  public int state_sessions_count {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_state_sessions_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_state_sessions_count_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_vx_state_session state_sessions {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_state_sessions_set(swigCPtr, SWIGTYPE_p_p_vx_state_session.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_state_sessions_get(swigCPtr);
      SWIGTYPE_p_p_vx_state_session ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_vx_state_session(cPtr, false);
      return ret;
    } 
  }

  public int in_delayed_playback {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_in_delayed_playback_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_in_delayed_playback_get(swigCPtr);
      return ret;
    } 
  }

  public double current_playback_speed {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_current_playback_speed_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_current_playback_speed_get(swigCPtr);
      return ret;
    } 
  }

  public vx_sessiongroup_playback_mode current_playback_mode {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_current_playback_mode_set(swigCPtr, (int)value);
    } 
    get {
      vx_sessiongroup_playback_mode ret = (vx_sessiongroup_playback_mode)VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_current_playback_mode_get(swigCPtr);
      return ret;
    } 
  }

  public int playback_paused {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_playback_paused_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_playback_paused_get(swigCPtr);
      return ret;
    } 
  }

  public int loop_buffer_capacity {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_loop_buffer_capacity_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_loop_buffer_capacity_get(swigCPtr);
      return ret;
    } 
  }

  public int first_loop_frame {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_first_loop_frame_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_first_loop_frame_get(swigCPtr);
      return ret;
    } 
  }

  public int total_loop_frames_captured {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_total_loop_frames_captured_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_total_loop_frames_captured_get(swigCPtr);
      return ret;
    } 
  }

  public int last_loop_frame_played {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_last_loop_frame_played_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_last_loop_frame_played_get(swigCPtr);
      return ret;
    } 
  }

  public string current_recording_filename {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_current_recording_filename_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_current_recording_filename_get(swigCPtr);
      return ret;
    } 
  }

  public int total_recorded_frames {
    set {
      VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_total_recorded_frames_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_sessiongroup_t_total_recorded_frames_get(swigCPtr);
      return ret;
    } 
  }

  public vx_state_sessiongroup_t() : this(VivoxCoreInstancePINVOKE.new_vx_state_sessiongroup_t(), true) {
  }

}
