//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_session_text_state {
  session_text_disconnected = 0,
  session_text_connected = 1,
  session_text_connecting = 2,
  session_text_disconnecting = 3
}
