//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_session_media_state {
  session_media_none = 0,
  session_media_disconnected = 1,
  session_media_connected = 2,
  session_media_ringing = 3,
  session_media_hold = 4,
  session_media_refer = 5,
  session_media_connecting = 6,
  session_media_disconnecting = 7
}
