//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_session_answer_mode {
  mode_none = 0,
  mode_auto_answer = 1,
  mode_verify_answer = 2,
  mode_busy_answer = 3
}
