//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_sessiongroup_playback_mode {
  VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL = 0,
  VX_SESSIONGROUP_PLAYBACK_MODE_VOX = 1
}
