//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_state_buddy_group_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_state_buddy_group_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_state_buddy_group_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_state_buddy_group_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_state_buddy_group_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int group_id {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_group_t_group_id_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_buddy_group_t_group_id_get(swigCPtr);
      return ret;
    } 
  }

  public string group_name {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_group_t_group_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_buddy_group_t_group_name_get(swigCPtr);
      return ret;
    } 
  }

  public string group_data {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_group_t_group_data_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_buddy_group_t_group_data_get(swigCPtr);
      return ret;
    } 
  }

  public vx_state_buddy_group_t() : this(VivoxCoreInstancePINVOKE.new_vx_state_buddy_group_t(), true) {
  }

}
