//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_stat_thread_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_stat_thread_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_stat_thread_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_stat_thread_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_stat_thread_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int interval {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_interval_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_interval_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_lt_1ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_1ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_1ms_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_lt_5ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_5ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_5ms_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_lt_10ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_10ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_10ms_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_lt_16ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_16ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_16ms_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_lt_20ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_20ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_20ms_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_lt_25ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_25ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_lt_25ms_get(swigCPtr);
      return ret;
    } 
  }

  public int count_poll_gte_25ms {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_gte_25ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_stat_thread_t_count_poll_gte_25ms_get(swigCPtr);
      return ret;
    } 
  }

  public vx_stat_thread_t() : this(VivoxCoreInstancePINVOKE.new_vx_stat_thread_t(), true) {
  }

}
