//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_sessiongroup_audio_injection_control_type {
  VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_STOP = 0,
  vx_sessiongroup_audio_injection_control_stop = VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_STOP,
  VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_START = 1,
  vx_sessiongroup_audio_injection_control_start = VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_START,
  VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_RESTART = 2,
  vx_sessiongroup_audio_injection_control_restart = VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_RESTART,
  VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_MIN = VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_STOP,
  vx_sessiongroup_audio_injection_control_min = vx_sessiongroup_audio_injection_control_stop,
  VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_MAX = VX_SESSIONGROUP_AUDIO_INJECTION_CONTROL_RESTART,
  vx_sessiongroup_audio_injection_control_max = vx_sessiongroup_audio_injection_control_restart
}
