//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_stat_sample_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_stat_sample_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_stat_sample_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_stat_sample_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_stat_sample_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double sample_count {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_sample_count_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_sample_count_get(swigCPtr);
      return ret;
    } 
  }

  public double sum {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_sum_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_sum_get(swigCPtr);
      return ret;
    } 
  }

  public double sum_of_squares {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_sum_of_squares_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_sum_of_squares_get(swigCPtr);
      return ret;
    } 
  }

  public double mean {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_mean_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_mean_get(swigCPtr);
      return ret;
    } 
  }

  public double stddev {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_stddev_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_stddev_get(swigCPtr);
      return ret;
    } 
  }

  public double min {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_min_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_min_get(swigCPtr);
      return ret;
    } 
  }

  public double max {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_max_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_max_get(swigCPtr);
      return ret;
    } 
  }

  public double last {
    set {
      VivoxCoreInstancePINVOKE.vx_stat_sample_t_last_set(swigCPtr, value);
    } 
    get {
      double ret = VivoxCoreInstancePINVOKE.vx_stat_sample_t_last_get(swigCPtr);
      return ret;
    } 
  }

  public vx_stat_sample_t() : this(VivoxCoreInstancePINVOKE.new_vx_stat_sample_t(), true) {
  }

}
