//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_session_handle_type {
  session_handle_type_unique = 0,
  session_handle_type_legacy = 1,
  session_handle_type_heirarchical_numeric = 2,
  session_handle_type_heirarchical_unique = 3
}
