//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_state_buddy_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_state_buddy_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_state_buddy_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_state_buddy_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_state_buddy_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string buddy_uri {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_t_buddy_uri_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_buddy_t_buddy_uri_get(swigCPtr);
      return ret;
    } 
  }

  public string display_name {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_t_display_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_buddy_t_display_name_get(swigCPtr);
      return ret;
    } 
  }

  public int parent_group_id {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_t_parent_group_id_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_buddy_t_parent_group_id_get(swigCPtr);
      return ret;
    } 
  }

  public string buddy_data {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_t_buddy_data_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_buddy_t_buddy_data_get(swigCPtr);
      return ret;
    } 
  }

  public int state_buddy_contact_count {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_t_state_buddy_contact_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_buddy_t_state_buddy_contact_count_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_vx_state_buddy_contact state_buddy_contacts {
    set {
      VivoxCoreInstancePINVOKE.vx_state_buddy_t_state_buddy_contacts_set(swigCPtr, SWIGTYPE_p_p_vx_state_buddy_contact.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_state_buddy_t_state_buddy_contacts_get(swigCPtr);
      SWIGTYPE_p_p_vx_state_buddy_contact ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_vx_state_buddy_contact(cPtr, false);
      return ret;
    } 
  }

  public vx_state_buddy_t() : this(VivoxCoreInstancePINVOKE.new_vx_state_buddy_t(), true) {
  }

}
