//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_sessiongroup_playback_control_type {
  VX_SESSIONGROUP_PLAYBACK_CONTROL_STOP = 0,
  VX_SESSIONGROUP_PLAYBACK_CONTROL_START = 1,
  VX_SESSIONGROUP_PLAYBACK_CONTROL_PAUSE = 3,
  VX_SESSIONGROUP_PLAYBACK_CONTROL_UNPAUSE = 4
}
