//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_state_session_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_state_session_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_state_session_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_state_session_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_state_session_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string session_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_session_handle_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_session_t_session_handle_get(swigCPtr);
      return ret;
    } 
  }

  public string uri {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_uri_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_session_t_uri_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_name_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_session_t_name_get(swigCPtr);
      return ret;
    } 
  }

  public int is_audio_muted_for_me {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_audio_muted_for_me_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_audio_muted_for_me_get(swigCPtr);
      return ret;
    } 
  }

  public int is_text_muted_for_me {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_text_muted_for_me_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_text_muted_for_me_get(swigCPtr);
      return ret;
    } 
  }

  public int is_transmitting {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_transmitting_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_transmitting_get(swigCPtr);
      return ret;
    } 
  }

  public int is_focused {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_focused_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_focused_get(swigCPtr);
      return ret;
    } 
  }

  public int volume {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_volume_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_volume_get(swigCPtr);
      return ret;
    } 
  }

  public int session_font_id {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_session_font_id_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_session_font_id_get(swigCPtr);
      return ret;
    } 
  }

  public int has_audio {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_has_audio_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_has_audio_get(swigCPtr);
      return ret;
    } 
  }

  public int has_text {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_has_text_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_has_text_get(swigCPtr);
      return ret;
    } 
  }

  public int is_incoming {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_incoming_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_incoming_get(swigCPtr);
      return ret;
    } 
  }

  public int is_positional {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_positional_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_positional_get(swigCPtr);
      return ret;
    } 
  }

  public int is_connected {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_is_connected_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_is_connected_get(swigCPtr);
      return ret;
    } 
  }

  public int state_participant_count {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_state_participant_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_state_session_t_state_participant_count_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_vx_state_participant state_participants {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_state_participants_set(swigCPtr, SWIGTYPE_p_p_vx_state_participant.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_state_session_t_state_participants_get(swigCPtr);
      SWIGTYPE_p_p_vx_state_participant ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_vx_state_participant(cPtr, false);
      return ret;
    } 
  }

  public string durable_media_id {
    set {
      VivoxCoreInstancePINVOKE.vx_state_session_t_durable_media_id_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_state_session_t_durable_media_id_get(swigCPtr);
      return ret;
    } 
  }

  public vx_state_session_t() : this(VivoxCoreInstancePINVOKE.new_vx_state_session_t(), true) {
  }

}
