//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_udp_frame_type {
  vx_frame_type_rtp = 0,
  vx_frame_type_rtcp = 1,
  vx_frame_type_sip_message = 2,
  vx_frame_type_sip_keepalive = 3
}
