//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VXA_CAPTURE_FLAGS {
  VXA_CAPTURE_OPEN_FLAG_USE_AEC = 0x00000001,
  VXA_CAPTURE_OPEN_FLAG_USE_AGC = 0x00000002
}
