//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VXA_ERROR_CODES {
  VXA_SUCCESS = 0,
  VXA_INVALID_PARAMETER = 1,
  VXA_DEVICE_DOES_NOT_EXIST = 2,
  VXA_INTERNAL_ERROR = 3,
  VXA_OUT_OF_MEMORY = 4,
  VXA_INVALID_STATE = 5,
  VXA_NO_MORE_DATA = 6,
  VXA_FEATURE_NOT_SUPPORTED = 7,
  VXA_MAX_DEVICES_EXCEEDED = 8,
  VXA_NO_BUFFERS_AVAILABLE = 9
}
