//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vxa_apcd_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vxa_apcd_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vxa_apcd_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vxa_apcd_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vxa_apcd_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_vxa_apcd__p_char pf_get_display_name {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_get_display_name_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd__p_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_get_display_name_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd__p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd__p_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_vxa_apcd__p_char pf_get_internal_name {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_get_internal_name_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd__p_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_get_internal_name_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd__p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd__p_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_vxa_apcd_int_int__int pf_open {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_open_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd_int_int__int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_open_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd_int_int__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd_int_int__int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_vxa_apcd__int pf_is_open {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_is_open_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd__int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_is_open_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd__int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_vxa_apcd_p_void_int__int pf_read {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_read_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd_p_void_int__int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_read_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd_p_void_int__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd_p_void_int__int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_vxa_apcd_p_vxa_capture_device_stats_t__int pf_get_stats {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_get_stats_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd_p_vxa_capture_device_stats_t__int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_get_stats_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd_p_vxa_capture_device_stats_t__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd_p_vxa_capture_device_stats_t__int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_vxa_apcd__int pf_close {
    set {
      VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_close_set(swigCPtr, SWIGTYPE_p_f_p_vxa_apcd__int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vxa_apcd_t_pf_close_get(swigCPtr);
      SWIGTYPE_p_f_p_vxa_apcd__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_vxa_apcd__int(cPtr, false);
      return ret;
    } 
  }

  public vxa_apcd_t() : this(VivoxCoreInstancePINVOKE.new_vxa_apcd_t(), true) {
  }

}
