//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef LIGHTINGDEBUG_CS_HLSL
#define LIGHTINGDEBUG_CS_HLSL
//
// UnityEngine.Experimental.Rendering.HDPipeline.DebugLightingMode:  static fields
//
#define DEBUGLIGHTINGMODE_NONE (0)
#define DEBUGLIGHTINGMODE_DIFFUSE_LIGHTING (1)
#define DEBUGLIGHTINGMODE_SPECULAR_LIGHTING (2)
#define DEBUGLIGHTINGMODE_LUX_METER (3)
#define DEBUGLIGHTINGMODE_LUMINANCE_METER (4)
#define DEBUGLIGHTINGMODE_VISUALIZE_CASCADE (5)
#define DEBUGLIGHTINGMODE_VISUALIZE_SHADOW_MASKS (6)
#define DEBUGLIGHTINGMODE_INDIRECT_DIFFUSE_OCCLUSION (7)
#define DEBUGLIGHTINGMODE_INDIRECT_SPECULAR_OCCLUSION (8)

//
// UnityEngine.Experimental.Rendering.HDPipeline.ShadowMapDebugMode:  static fields
//
#define SHADOWMAPDEBUGMODE_NONE (0)
#define SHADOWMAPDEBUGMODE_VISUALIZE_ATLAS (1)
#define SHADOWMAPDEBUGMODE_VISUALIZE_SHADOW_MAP (2)
#define SHADOWMAPDEBUGMODE_SINGLE_SHADOW (3)


#endif
