//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef MIPMAPDEBUG_CS_HLSL
#define MIPMAPDEBUG_CS_HLSL
//
// UnityEngine.Experimental.Rendering.HDPipeline.DebugMipMapMode:  static fields
//
#define DEBUGMIPMAPMODE_NONE (0)
#define DEBUGMIPMAPMODE_MIP_RATIO (1)
#define DEBUGMIPMAPMODE_MIP_COUNT (2)
#define DEBUGMIPMAPMODE_MIP_COUNT_REDUCTION (3)
#define DEBUGMIPMAPMODE_STREAMING_MIP_BUDGET (4)
#define DEBUGMIPMAPMODE_STREAMING_MIP (5)

//
// UnityEngine.Experimental.Rendering.HDPipeline.DebugMipMapModeTerrainTexture:  static fields
//
#define DEBUGMIPMAPMODETERRAINTEXTURE_CONTROL (0)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER0 (1)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER1 (2)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER2 (3)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER3 (4)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER4 (5)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER5 (6)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER6 (7)
#define DEBUGMIPMAPMODETERRAINTEXTURE_LAYER7 (8)


#endif
